weights: yolov5x.pt
cfg: models/yolov5x_kaist-rgbt.yaml
data: data/kaist-rgbt.yaml
hyp:
  lr0: 0.03
  lrf: 0.12
  momentum: 0.937
  weight_decay: 0.0004
  warmup_epochs: 2.0
  warmup_momentum: 0.6
  warmup_bias_lr: 0.1
  box: 0.03
  cls: 0.25
  cls_pw: 0.8
  obj: 0.4
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.0
  degrees: 0.0
  translate: 0.0
  scale: 0.0
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.0
  mosaic: 1.0
  mixup: 0.5
  copy_paste: 0.0
epochs: 30
batch_size: 12
imgsz: 640
rect: false
resume: false
nosave: false
noval: true
noautoanchor: false
noplots: false
evolve: 300
evolve_population: data/hyps
resume_evolve: null
bucket: ''
cache: null
image_weights: true
device: '3'
multi_scale: true
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: pedestrian
name: yolov5x-rgbt-new2012
exist_ok: false
quad: true
cos_lr: false
label_smoothing: 0.0
patience: 100
save_period: -1
seed: 0
local_rank: -1
rgbt: true
entity: comflife
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: pedestrian/yolov5x-rgbt-new2012
